server:
  port: 6060
  
spring:
  cloud:
    gateway:
      routes:
      - id: plans-api
        uri: lb://PLANS-API
        predicates:
        - Path=/plans
      - id: greet-api
        uri: lb://GREET-API
        predicates:
        - Path=/greet

  application:
    name: CLOUD-API-GATEWAY
