spring:
  boot:
    admin:
      client:
        url: http://localhost:9090/
 
  datasource:
    url: jdbc:mysql://localhost:3306/citizen_db
    username: root
    password: root
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: kuntalpaul2015joint@gmail.com
    password: raiy iiyd xazi bkqu
    properties:
      mail:
        smtp:
          auth: true
      
          starttls:
            enable: true
        